2019-12-04 20:46:58,599 : INFO : Machine : Mission Pinball Framework Core Engine v0.52.7
2019-12-04 20:46:58,599 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'mpfconfigfile': '/usr/local/lib/python3.7/dist-packages/mpf/mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs/2019-12-04-20-46-58-mpf-raspberrypi.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'smart_virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-12-04 20:46:58,599 : INFO : Machine : MPF path: /usr/local/lib/python3.7/dist-packages/mpf
2019-12-04 20:46:58,600 : INFO : Machine : Machine path: /home/pi/HotTipEM
2019-12-04 20:46:58,600 : INFO : Machine : Platform: linux
2019-12-04 20:46:58,600 : INFO : Machine : Python executable location: /usr/bin/python3
2019-12-04 20:46:58,600 : INFO : Machine : Python version: 3.7.3 (32-bit)
2019-12-04 20:46:58,600 : INFO : Machine : Machine config file #1: config.yaml
2019-12-04 20:46:58,602 : WARNING : ConfigProcessor : Cache file not found: /tmp/97a0759ee607251f80db56c9576ff30a.mpf_cache
2019-12-04 20:46:58,602 : INFO : ConfigProcessor : Loading config from file /usr/local/lib/python3.7/dist-packages/mpf/mpfconfig.yaml.
2019-12-04 20:46:58,827 : INFO : ConfigProcessor : Loading config: /usr/local/lib/python3.7/dist-packages/mpf/mpfconfig.yaml
2019-12-04 20:46:58,854 : INFO : ConfigProcessor : Loading config from file /home/pi/HotTipEM/config/config.yaml.
2019-12-04 20:46:58,884 : INFO : ConfigProcessor : Loading config: /home/pi/HotTipEM/config/config.yaml
2019-12-04 20:46:58,887 : INFO : ConfigProcessor : Config file cache created: /tmp/97a0759ee607251f80db56c9576ff30a.mpf_cache
2019-12-04 20:46:58,889 : INFO : Machine : Initialise MPF.
2019-12-04 20:46:58,996 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2019-12-04 20:46:59,056 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.52.7', 'prev_value': None, 'change': True}
2019-12-04 20:46:59,056 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.52.7, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2019-12-04 20:46:59,056 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.7.3', 'prev_value': None, 'change': True}
2019-12-04 20:46:59,058 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Linux-4.19.75-v7l+-armv7l-with-debian-10.2', 'prev_value': None, 'change': True}
2019-12-04 20:46:59,059 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Linux', 'prev_value': None, 'change': True}
2019-12-04 20:46:59,059 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '4.19.75-v7l+', 'prev_value': None, 'change': True}
2019-12-04 20:46:59,059 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '#1270 SMP Tue Sep 24 18:51:41 BST 2019', 'prev_value': None, 'change': True}
2019-12-04 20:46:59,059 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'armv7l', 'prev_value': None, 'change': True}
2019-12-04 20:46:59,059 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2019-12-04 20:46:59,128 : INFO : ConfigProcessor : Loading config from cache: /tmp/7559345efe69122f4d6fb5f65214b482.mpf_cache
2019-12-04 20:46:59,137 : INFO : ConfigProcessor : Loading config from cache: /tmp/0488c24d6cb11f71168a087186f8afaf.mpf_cache
2019-12-04 20:46:59,152 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...not defined')>) at /usr/local/lib/python3.7/dist-packages/mpf/core/events.py:96
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...not defined')>) at /usr/local/lib/python3.7/dist-packages/mpf/core/events.py:96>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/events.py", line 99, in _async_handler_done
    future.result()
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/device_manager.py", line 113, in _load_device_modules
    self.load_devices_config(validate=True)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/device_manager.py", line 177, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/device.py", line 105, in validate_and_parse_config
    self.config_section, config, self.name, "device", prefix=debug_prefix)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 268, in validate_config
    validation_failure_info=(validation_failure_info, k))
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 315, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 711, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 458, in _validate_type_machine
    6)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 731, in validation_error
    item, msg), 5 if code is None else code, self.log.name)
mpf.exceptions.ConfigFileError.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry ball_devices:bd_trough:ball_switches = "s_outhole" is not valid. Device s_outhole of type switches not defined Error Code: CFE-ConfigValidator-6
2019-12-04 20:46:59,164 : INFO : Machine : Starting the main run loop.
2019-12-04 20:46:59,165 : INFO : Machine : Shutting down...
2019-12-04 20:46:59,165 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2019-12-04 20:46:59,169 : ERROR : root : Config File Error in ConfigValidator: Config validation error: Entry ball_devices:bd_trough:ball_switches = "s_outhole" is not valid. Device s_outhole of type switches not defined Error Code: CFE-ConfigValidator-6
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mpf/commands/game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/machine.py", line 709, in run
    self._run_loop()
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/machine.py", line 769, in _run_loop
    raise self._exception['exception']
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/events.py", line 99, in _async_handler_done
    future.result()
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/device_manager.py", line 113, in _load_device_modules
    self.load_devices_config(validate=True)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/device_manager.py", line 177, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/device.py", line 105, in validate_and_parse_config
    self.config_section, config, self.name, "device", prefix=debug_prefix)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 268, in validate_config
    validation_failure_info=(validation_failure_info, k))
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 315, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 711, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 458, in _validate_type_machine
    6)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 731, in validation_error
    item, msg), 5 if code is None else code, self.log.name)
mpf.exceptions.ConfigFileError.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry ball_devices:bd_trough:ball_switches = "s_outhole" is not valid. Device s_outhole of type switches not defined Error Code: CFE-ConfigValidator-6
